tilemap:
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$00,$fe,$fe
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$00,$fe,$fe
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$00,$fe,$fe
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$00,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$00,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$00,$fe,$fe,$fe,$fc,$fe,$fe,$00,$fe,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fe,$fe,$fc,$00,$fe,$fe,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fe,$fe,$fe,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fe,$fe,$fe
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
levels:
    db $02,$fc,$00,$fe,$fe,$fe,$fc,$00,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$00,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$00,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fc,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fe,$fc,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$00,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$00,$fe,$fc,$fe,$fe,$00,$fc,$fe,$00
    db $02,$fc,$fe,$fe,$00,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$00,$fe,$fe,$fe,$fe,$fe,$fc,$00,$fe,$fe,$fe,$fe,$fe,$fe
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00,$fc,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
    db $02,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fc,$fe,$fe,$fe,$fe,$00
    db $02,$fc,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe,$00
